import { Opportunity } from './types';

export const opportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Frontend Developer Intern',
    organization: 'Kabul Tech Community',
    category: 'Internship',
    location: 'Kabul',
    type: 'Remote',
    deadline: '2026-07-30T00:00:00.000Z',
    description: 'Beginner friendly internship for React developers.',
    requirements: ['HTML', 'CSS', 'React'],
    applyLink: '#',
    tags: ['React', 'Frontend'],
    featured: true,
  },
  {
    id: '2',
    title: 'Remote UI Designer',
    organization: 'Global Studio',
    category: 'Remote',
    location: 'Online',
    type: 'Remote',
    deadline: '2026-08-20T00:00:00.000Z',
    description: 'Work remotely as UI designer.',
    requirements: ['Figma', 'UI Design'],
    applyLink: '#',
    tags: ['Design', 'Figma'],
    featured: true,
  },
  {
    id: '3',
    title: 'Women in Tech Scholarship',
    organization: 'Global Learning Foundation',
    category: 'Scholarship',
    location: 'Online',
    type: 'Remote',
    deadline: '2026-08-10T00:00:00.000Z',
    description: 'Scholarship for women who want to study technology online.',
    requirements: ['Basic English', 'Motivation letter'],
    applyLink: '#',
    tags: ['Scholarship', 'Women', 'Online'],
    featured: true,
  },
  {
    id: '4',
    title: 'Backend Developer',
    organization: 'Herat Startup Hub',
    category: 'Job',
    location: 'Herat',
    type: 'OnSite',
    deadline: '2026-07-25T00:00:00.000Z',
    description: 'Backend developer position at a growing startup in Herat.',
    requirements: ['Node.js', 'PostgreSQL', 'REST API'],
    applyLink: '#',
    tags: ['Backend', 'Node.js'],
  },
  {
    id: '5',
    title: 'Data Entry Specialist',
    organization: 'UN Afghanistan',
    category: 'Job',
    location: 'Kabul',
    type: 'OnSite',
    deadline: '2026-08-01T00:00:00.000Z',
    description: 'Data entry and management role at UN Afghanistan office.',
    requirements: ['MS Office', 'Attention to detail'],
    applyLink: '#',
    tags: ['Data', 'UN'],
  },
  {
    id: '6',
    title: 'React Developer',
    organization: 'Tech4Good',
    category: 'Job',
    location: 'Online',
    type: 'Remote',
    deadline: '2026-08-15T00:00:00.000Z',
    description: 'Remote React developer for NGO projects.',
    requirements: ['React', 'TypeScript', 'Git'],
    applyLink: '#',
    tags: ['React', 'Remote'],
    featured: true,
  },
  {
    id: '7',
    title: 'UI/UX Designer',
    organization: 'Creative Agency',
    category: 'Job',
    location: 'Kabul',
    type: 'Remote',
    deadline: '2026-07-29T00:00:00.000Z',
    description: 'UI/UX designer for digital products.',
    requirements: ['Figma', 'User Research', 'Prototyping'],
    applyLink: '#',
    tags: ['Design', 'UX'],
  },
  {
    id: '8',
    title: 'Digital Marketing Internship',
    organization: 'Afghan Media Group',
    category: 'Internship',
    location: 'Kabul',
    type: 'OnSite',
    deadline: '2026-08-10T00:00:00.000Z',
    description: 'Learn digital marketing with a leading Afghan media company.',
    requirements: ['Social Media', 'Content Writing'],
    applyLink: '#',
    tags: ['Marketing', 'Internship'],
  },
];